### ISSUE TITLE
update llir/llvm to support LLVM 10.0

### ISSUE THREAD

**Issue by mewmew** [llir/llvm#128]
This is a meta issue tracking the progress to support LLVM 10.0 in llir/llvm.

For reference, it will be very similar to the [work done to support LLVM 9.0](https://github.com/llir/llvm/issues?utf8=%E2%9C%93&q=label%3A%22llvm+9.0%22).

In particular, we need to:
* update the grammar to LLVM 10.0 (see #101 as reference)
   - [llir/grammar](https://github.com/llir/grammar)
* update the test cases to LLVM 10.0 (see #105 as reference)
   - [llir/testdata](https://github.com/llir/testdata)
* add new language constructs of LLVM 10.0 (see #106 as reference)
   - [llir/llvm/ir](https://github.com/llir/llvm)

Release candidate 2 of LLVM 10.0 was tagged on the 11th of February, and the final release is scheduled for the 26th of February.

cc: @dannypsnl would you care to take a look at this? I can help out if you get stuck anywhere. I tried to write in the issues (#101, #105 and #106 and associated PRs) how we did this last time :) Just let me know if anything feels unclear.

Cheers,
Robin

**Comment by dannypsnl** [comment]
Just take a look, seems like LLVM 10 haven't released yet.

1. The latest tagged release note was 9.0.1(but it returns 404, I have no idea what happened)
2. https://github.com/llvm/llvm-project/releases shows 10 is in rc
3. [latest release note](https://llvm.org/docs/ReleaseNotes.html)'s content is empty right now

**Comment by mewmew** [comment]
> Just take a look, seems like LLVM 10 haven't released yet.

Yeah, lets wait until 10.0 is released. I was just excited :)

**Comment by mewmew** [comment]
[LLVM release candidate 5](https://github.com/llvm/llvm-project/releases/tag/llvmorg-10.0.0-rc5) is out. We are getting closer :)

**Comment by mewmew** [comment]
[LLVM 10.0](https://github.com/llvm/llvm-project/releases/tag/llvmorg-10.0.0) has finally been released :)

@dannypsnl, do you wanna take a look at updating `llir/llvm`? I'd be happy to support you and help if you get stuck :)

**Comment by dannypsnl** [comment]
Sure, I would take a look tomorrow :).

**Comment by dannypsnl** [comment]
# LLVM 10.0 Changes Report

[reference document](https://releases.llvm.org/10.0.0/docs/ReleaseNotes.html)

> ### Changes to the LLVM IR
> - Unnamed function arguments now get printed with their automatically generated name (e.g. “i32 %0”) in definitions.
    This may require front-ends to update their tests;
    if so there is a script utils/add_argument_names.py that correctly converted 80-90% of Clang tests.
    Some manual work will almost certainly still be needed.
> - A new `freeze` instruction is added.
    The `freeze` instruction is used to stop IR-level propagation of undef and poison values.
    Currently its support is preliminary; a freeze-equivalent operation for SelDag/MIR needs to be added.

### TODO:

- [ ] give parameter default name
- [ ] provide `freeze` instruction

**Comment by mewmew** [comment]
From the "Parse errors" section of https://github.com/llir/llvm/issues/132#issue-588625688 a couple of test cases are listed for which we need to update the grammar to LLVM 10.0.

They include:
* [ ] `nnan` used in `phi` instructions
* [ ] `!DIModule` metadata

**Comment by mewmew** [comment]
@dannypsnl, is it only the `freeze` instruction left for LLVM 10.0? Let me know if you get stuck or want to bounce a few ideas on how to implement the last few things for 10.0.

**Comment by mewmew** [comment]
With #137 merged, all new language concepts of LLVM 10.0 have been added to `llir/llvm`. Thanks @dannypsnl! :)

What remains to add for LLVM 10.0 is only enum values.

From https://github.com/llir/llvm/issues/132#issuecomment-610325470

* [ ] New calling conventions:

```diff
@@ -585,6 +585,7 @@ lltok::Kind LLLexer::LexIdentifier() {
   KEYWORD(ccc);
   KEYWORD(fastcc);
   KEYWORD(coldcc);
+  KEYWORD(cfguard_checkcc);
   KEYWORD(x86_stdcallcc);
   KEYWORD(x86_fastcallcc);
   KEYWORD(x86_thiscallcc);
@@ -593,6 +594,7 @@ lltok::Kind LLLexer::LexIdentifier() {
   KEYWORD(arm_aapcscc);
   KEYWORD(arm_aapcs_vfpcc);
   KEYWORD(aarch64_vector_pcs);
+  KEYWORD(aarch64_sve_vector_pcs);
   KEYWORD(msp430_intrcc);
   KEYWORD(avr_intrcc);
   KEYWORD(avr_signalcc);
@@ -622,6 +624,7 @@ lltok::Kind LLLexer::LexIdentifier() {
   KEYWORD(amdgpu_ps);
   KEYWORD(amdgpu_cs);
   KEYWORD(amdgpu_kernel);
+  KEYWORD(tailcc);
```

* `alwaysInline` keyword. It is only used in module summaries (#43). We can skip this for now. Adding modules summaries is an old issue, and so far noone has needed this?

* [ ] `nofree` as parameter attribute (currently only used for `FuncAttr` in grammar).

**Comment by mewmew** [comment]
After merging #128 and llir/testdata#6, the only test case remaining for LLVM 10.0 integration is [testdata/llvm/test/Bitcode/calling-conventions.3.2.ll](https://github.com/llir/testdata/blob/a89e79b09f71f6b16f06ac206c55a85a3fcc53cd/llvm/test/Bitcode/calling-conventions.3.2.ll#L29).

```
--- FAIL: TestParseFile (40.55s)
    asm_test.go:516: unable to parse "../testdata/llvm/test/Bitcode/calling-conventions.3.2.ll" into AST; syntax error at line 29
        unable to parse "../testdata/llvm/test/Bitcode/calling-conventions.3.2.ll" into an AST
```

**Comment by mewmew** [comment]
@dannypsnl I think with #140 merged, we are now ready to close this issue as `llir/llvm` is now udpated to LLVM 10.0. Is there anything else you can think of that should be worked on? Otherwise, feel free to close this issue :)
